# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [3]:
import numpy as np

## To Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size = (5, 5))
print("Original array:")
print(array)

## To replace all the elements in the third column with 1
array[:, 2] = 1
print("Modified array:")
print(array)


Original array:
[[ 3  4 17  1  3]
 [ 6  5 14  6  3]
 [15 12  8 17 12]
 [ 7  5 12 19  3]
 [11 16  6  4  3]]
Modified array:
[[ 3  4  1  1  3]
 [ 6  5  1  6  3]
 [15 12  1 17 12]
 [ 7  5  1 19  3]
 [11 16  1  4  3]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [4]:

## To Create a NumPy array of shape (4, 4) with values from 1 to 16
array = np.arange(1, 17).reshape(4, 4)  # np.random.randint(1, 17, size = (4, 4))
print("Original array:")
print(array)

## To Replace the diagonal elements with 0
np.fill_diagonal(array, 0)
print("Modified array:")
print(array)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [5]:
## To Create a NumPy array of shape (6, 6) with values from 1 to 36
array = np.arange(1, 37).reshape(6, 6)
print("Original array:")
print(array)

## To Extract the sub-array
sub_array = array[2:5, 1:4]
print("Sub-array:")
print(sub_array)

Original array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-array:
[[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [6]:
## To Create a NumPy array of shape (5, 5) with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

## To Extract the elements on the border
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, -1], array[1:-1, 0]))
print("Border elements:")
print(border_elements)


Original array:
[[14 20  3  1  1]
 [10 15  9 14 17]
 [12 11 16  8  3]
 [ 4  6  4 18  9]
 [20  9 14  1 16]]
Border elements:
[14 20  3  1  1 20  9 14  1 16 17  3  9 10 12  4]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [7]:
## To Create two NumPy arrays of shape (3, 4) filled with random integers
array1 = np.random.randint(1, 50, size=(3, 4))
array2 = np.random.randint(1, 50, size=(3, 4))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

## To Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)

Array 1:
[[39 37  4 29]
 [ 1 34  6  6]
 [25 10 44 16]]
Array 2:
[[47 25 18 46]
 [33 10 49 32]
 [43 30 15  7]]
Element-wise addition:
[[86 62 22 75]
 [34 44 55 38]
 [68 40 59 23]]
Element-wise subtraction:
[[ -8  12 -14 -17]
 [-32  24 -43 -26]
 [-18 -20  29   9]]
Element-wise multiplication:
[[1833  925   72 1334]
 [  33  340  294  192]
 [1075  300  660  112]]
Element-wise division:
[[0.82978723 1.48       0.22222222 0.63043478]
 [0.03030303 3.4        0.12244898 0.1875    ]
 [0.58139535 0.33333333 2.93333333 2.28571429]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [8]:
## Create a NumPy array of shape (4, 4) with values from 1 to 16
array = np.arange(1, 17).reshape(4, 4)
print("Original array:")
print(array)

## To Compute the row-wise and column-wise sum
row_sum = np.sum(array, axis = 1)
column_sum = np.sum(array, axis = 0)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(column_sum)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum:
[10 26 42 58]
Column-wise sum:
[28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [9]:
## To Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

## Compute the statistical values
mean = np.mean(array) 
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

Original array:
[[20 20  7 20 17]
 [ 5 13 12  6 17]
 [ 2  2 18 18  3]
 [ 2 14 18 13 19]
 [12 16 12 12 20]]
Mean: 12.72
Median: 13.0
Standard Deviation: 6.20657715653322
Variance: 38.5216


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [10]:
## To Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

## To Normalize the array
mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev

print("Normalized array:")
print(normalized_array)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [11]:
## To Create a NumPy array of shape (3, 3) filled with random integers
array = np.random.randint(1, 5, size=(3, 3))
row_array = np.random.randint(1, 5, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

## Add the 1D array to each row of the 2D array using broadcasting
result = array + row_array
print("Resulting array:")
print(result)

Original array:
[[4 2 4]
 [4 4 4]
 [3 3 1]]
1D array:
[1 4 1]
Resulting array:
[[5 6 5]
 [5 8 5]
 [4 7 2]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [12]:
## To Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 7, size=(4, 4))
column_array = np.random.randint(1, 7, size=(4,))
print("Original array:")
print(array)
print("1D array:")
print(column_array)

## To Subtract the 1D array from each column of the 2D array using broadcasting
result = array - column_array[:, None] # array - column_array[:, np.newaxis]
print("Resulting array:")
print(result)

Original array:
[[2 4 3 6]
 [2 5 3 1]
 [4 3 3 2]
 [5 6 2 4]]
1D array:
[4 3 2 3]
Resulting array:
[[-2  0 -1  2]
 [-1  2  0 -2]
 [ 2  1  1  0]
 [ 2  3 -1  1]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [13]:
## To Create a NumPy array of shape (3, 3) representing a matrix
matrix = np.random.randint(1, 50, size=(3, 3))
print("Original matrix:")
print(matrix)

## To Compute the determinant
det = np.linalg.det(matrix)
print("Determinant:", det)

## To Compute the inverse
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

## Compute the eigenvalues
e_values = np.linalg.eigvals(matrix)
print("Eigenvalues:", e_values)

Original matrix:
[[13 38 14]
 [10 11 48]
 [24 35 25]]
Determinant: 17215.0
Inverse:
[[-0.08161487 -0.02672088  0.09700842]
 [ 0.05239617 -0.00063898 -0.02811502]
 [ 0.00499564  0.02654662 -0.01376706]]
Eigenvalues: [ 74.34773872+0.j         -12.67386936+8.42140672j
 -12.67386936-8.42140672j]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [14]:
## To Create two NumPy arrays of shape (2, 3) and (3, 2)
array1 = np.arange(1, 7).reshape(2, 3)
array2 = np.arange(1, 7).reshape(3, 2)
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

## To Perform matrix multiplication
result = np.dot(array1, array2)             # result = np.matmul(array1, array2)
print("Matrix multiplication result:")
print(result)

Array 1:
[[1 2 3]
 [4 5 6]]
Array 2:
[[1 2]
 [3 4]
 [5 6]]
Matrix multiplication result:
[[22 28]
 [49 64]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [15]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

## To Reshape the array to shape (1, 9)
reshaped_array_1 = array.reshape((1,9))
print("Reshaped array (1, 9):")
print(reshaped_array_1)

# Reshape the array to shape (9, 1)
reshaped_array_2 = reshaped_array_1.reshape((9,1))
print("Reshaped array (9, 1):")
print(reshaped_array_2)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array (1, 9):
[[1 2 3 4 5 6 7 8 9]]
Reshaped array (9, 1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [16]:
## To Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 50, size=(5, 5))
print("Original array:")
print(array)

## To Flatten the array
flattened_array = array.flatten()   # array.reshape(-1)
print("Flattened array:")
print(flattened_array)

## To Reshape the array back to (5, 5)
reshaped_array = flattened_array.reshape(5, 5)
print("Reshaped array:")
print(reshaped_array)

Original array:
[[26 19 44  4 32]
 [41 11 45  4 36]
 [17 34 28 25 11]
 [49 44 38 46 24]
 [14 32 15 25 48]]
Flattened array:
[26 19 44  4 32 41 11 45  4 36 17 34 28 25 11 49 44 38 46 24 14 32 15 25
 48]
Reshaped array:
[[26 19 44  4 32]
 [41 11 45  4 36]
 [17 34 28 25 11]
 [49 44 38 46 24]
 [14 32 15 25 48]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [24]:
## To Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(10, 20, size=(5, 5))
print("Original array:")
print(array)

## To Use fancy indexing to extract the elements at the corners of the array
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

Original array:
[[18 11 15 12 10]
 [18 19 15 18 16]
 [16 17 19 13 15]
 [11 16 17 19 18]
 [10 10 10 10 12]]
Corner elements:
[18 10 10 12]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [26]:
## To Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array)

#E To Use boolean indexing to set all elements greater than 10 to 10
boolean_mask = array > 10
array[boolean_mask] = 10
print("Modified array:")
print(array)

Original array:
[[ 2 18  6  3]
 [ 3 12  9 17]
 [ 4  4  5  1]
 [13 18  6 13]]
Modified array:
[[ 2 10  6  3]
 [ 3 10  9 10]
 [ 4  4  5  1]
 [10 10  6 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [30]:
## To Create a structured array with fields 'name', 'age', and 'weight'
data_type = [("name", (np.str_, 20)), ("age", np.int32), ("weight", np.float64)]

# data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]

data = np.array([("ram", 25, 55.5), ("shyam", 30, 85.3), ("hari", 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

## To Sort the array by age
sorted_data = np.sort(data, order = "age")
print("Sorted array by age:")
print(sorted_data)


Original array:
[('ram', 25, 55.5) ('shyam', 30, 85.3) ('hari', 20, 65.2)]
Sorted array by age:
[('hari', 20, 65.2) ('ram', 25, 55.5) ('shyam', 30, 85.3)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [37]:
## To Create a structured array with fields 'x' and 'y'
data_type = [("x", np.int32), ("y", np.int32)]

#data_type = [('x', 'i4'), ('y', 'i4')]

data = np.array([(1, 10), (2, 20), (3, 30), (4, 40)], dtype=data_type)
print("Original array:")
print(data)

## Compute the Euclidean distance between each pair of points
distances = np.sqrt((data["x"][:, np.newaxis] -data["x"])**2 + (data["y"][:,np.newaxis] - data["y"])**2)
print("Euclidean distances:")
print(distances)


Original array:
[(1, 10) (2, 20) (3, 30) (4, 40)]
Euclidean distances:
[[ 0.         10.04987562 20.09975124 30.14962686]
 [10.04987562  0.         10.04987562 20.09975124]
 [20.09975124 10.04987562  0.         10.04987562]
 [30.14962686 20.09975124 10.04987562  0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [39]:
import numpy.ma as ma

## To Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_array(array, mask= (array > 10))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

## To Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[11 20  2 11]
 [ 7  8  4  9]
 [ 8 13 12 12]
 [10  4 19  6]]
Masked array:
[[-- -- 2 --]
 [7 8 4 9]
 [8 -- -- --]
 [10 4 -- 6]]
Sum of unmasked elements: 58


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [42]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask = np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)



Original array:
[[15 14  5]
 [18  9 17]
 [13  2 13]]
Masked array:
[[-- 14 5]
 [18 -- 17]
 [13 2 --]]
Modified masked array:
[[11 14  5]
 [18 11 17]
 [13  2 11]]
